/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    Athletes: () => import('#controllers/admin/athletes_controller'),
    Dashboard: () => import('#controllers/admin/dashboard_controller'),
    Scores: () => import('#controllers/admin/scores_controller'),
  },
  Home: () => import('#controllers/home_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
}
