/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AthleteSchema extends BaseModel {
  static $columns = ['bib', 'className', 'createdAt', 'eventsJson', 'gender', 'houseId', 'id', 'name', 'updatedAt'] as const
  $columns = AthleteSchema.$columns
  @column()
  declare bib: string
  @column()
  declare className: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventsJson: any | null
  @column()
  declare gender: string
  @column()
  declare houseId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EventResultSchema extends BaseModel {
  static $columns = ['athleteName', 'bib', 'createdAt', 'eventId', 'houseId', 'id', 'isRecordBroken', 'lane', 'medal', 'place', 'points', 'recordValue', 'updatedAt'] as const
  $columns = EventResultSchema.$columns
  @column()
  declare athleteName: string
  @column()
  declare bib: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventId: string
  @column()
  declare houseId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isRecordBroken: boolean | null
  @column()
  declare lane: number | null
  @column()
  declare medal: string
  @column()
  declare place: number
  @column()
  declare points: number
  @column()
  declare recordValue: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EventSchema extends BaseModel {
  static $columns = ['category', 'code', 'createdAt', 'eventName', 'id', 'scheduledTime', 'stage', 'status', 'type', 'updatedAt'] as const
  $columns = EventSchema.$columns
  @column()
  declare category: string
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare scheduledTime: string
  @column()
  declare stage: string
  @column()
  declare status: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class HouseSchema extends BaseModel {
  static $columns = ['badgeBg', 'bronzeMedals', 'color', 'createdAt', 'fourthPlaces', 'goldMedals', 'id', 'lightBg', 'motto', 'name', 'points', 'rank', 'silverMedals', 'updatedAt'] as const
  $columns = HouseSchema.$columns
  @column()
  declare badgeBg: string
  @column()
  declare bronzeMedals: number | null
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fourthPlaces: number | null
  @column()
  declare goldMedals: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lightBg: string
  @column()
  declare motto: string
  @column()
  declare name: string
  @column()
  declare points: number | null
  @column()
  declare rank: number | null
  @column()
  declare silverMedals: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
